### ISSUE TITLE
Install Ubuntu 20.04 LTS not working globally

### ISSUE THREAD

**Issue by feliperoschel** [AwesomeDocs/cli#3]
Hi folks,

I'm struggling with the setup following the tutorial. 

I tried both ways, using "go get" and the "binaries" but cannot get it working globally. It there any other more detailed tutorial I could follow? Go commands are working perfectly.

Terminal
```
➜  ~ go version
go version go1.16 linux/amd64
➜  ~ docxy
zsh: command not found: docxy
```

Path
```
/home/froschel/.zshrc
/home/froschel/.profile
/home/froschel/.bashrc

export PATH=$PATH:/usr/local/go/bin
```

go get -u github.com/docxy/docxy command keeps installing the docxy files at:
```
/home/froschel/go
```

Regards

**Comment by iamtraction** [comment]
Since `go get` is installing packages to `/home/froschel/go`, that's your `GOPATH`. So, you need to add `/home/froschel/go/bin` to your `PATH`. Then you can access `docxy` globally, or any package installed via go for that matter.
